# DigitalOcean App Platform Configuration
# This file configures deployment via GitHub integration

name: island-bitcoin

# GitHub repository connection (configured in DO console)
# repo: yourusername/islandbitcoin-web
# branch: main
# source_dir: public_html

# Services
services:
  # Web service (unified server)
  - name: web
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm run start:prod
    http_port: 3000
    
    # Instance configuration
    instance_size_slug: basic-xxs  # $4/month
    instance_count: 1
    
    # Environment variables (set in DO console)
    envs:
      - key: NODE_ENV
        value: production
        type: GENERAL
      - key: PORT
        value: "3000"
        type: GENERAL
      - key: API_SECRET
        type: SECRET
        value: "ENCRYPTED"
      - key: REDIS_URL
        type: SECRET
        value: "${redis.DATABASE_URL}"
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      
# Databases
databases:
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-1vcpu-1gb  # $15/month
    num_nodes: 1

# Static sites (optional - if you want to separate frontend)
# static_sites:
#   - name: frontend
#     build_command: npm install && npm run build
#     output_dir: dist
#     environment_slug: html

# Jobs (optional - for scheduled tasks)
# jobs:
#   - name: cleanup
#     kind: POST_DEPLOY
#     run_command: node scripts/cleanup.js

# App-level environment variables
envs:
  - key: NODE_VERSION
    value: "20"
    scope: BUILD_TIME