version: '3.8'

services:
  # Island Bitcoin app
  island-bitcoin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: island-bitcoin
    restart: unless-stopped
    # Use internal port, Nginx will proxy
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_SECRET=${API_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - apps-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  # Redis for Island Bitcoin
  redis:
    image: redis:7-alpine
    container_name: island-bitcoin-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - apps-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy for both apps
  nginx:
    image: nginx:alpine
    container_name: apps-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-multi-app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - island-bitcoin
    networks:
      - apps-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  apps-network:
    driver: bridge

volumes:
  redis-data: