# DigitalOcean App Platform Spec
# This is the official App Platform configuration format

spec:
  name: island-bitcoin
  region: nyc
  
  services:
    - name: island-bitcoin-web
      github:
        repo: YOUR_GITHUB_USERNAME/islandbitcoin-web
        branch: main
        deploy_on_push: true
      source_dir: public_html
      
      # Build configuration
      build_command: npm install && npm run build
      run_command: node server/unified-server.js
      
      # Environment
      environment_slug: node-js
      http_port: 3000
      
      # Resources
      instance_size_slug: basic-xxs
      instance_count: 1
      
      # Environment variables
      envs:
        - key: NODE_ENV
          value: production
        - key: PORT
          value: "3000"
        - key: API_SECRET
          value: ${API_SECRET}
          type: SECRET
        - key: REDIS_URL
          value: ${island-bitcoin-redis.DATABASE_URL}
          scope: RUN_TIME
      
      # Routes
      routes:
        - path: /
      
      # Health check
      health_check:
        http_path: /api/health
        timeout_seconds: 10
        port: 3000
  
  databases:
    - name: island-bitcoin-redis
      engine: REDIS
      version: "7"
      size: db-s-1vcpu-1gb
      num_nodes: 1